### ISSUE TITLE
Feature Request: Pink React Component Text Input Placeholder Support & More

### ISSUE THREAD

**Issue by denizsokullu** [carbon-design-system/carbon-addons-ics#26]
## Detailed description

Hi, I was trying to use the text input component and realized that there is no support for a placeholder.
I went into the source code, replaced the null with a string and got a visual bug also.

<img width="212" alt="screen shot 2018-03-22 at 4 13 06 pm" src="https://user-images.githubusercontent.com/15388560/37796279-465a4362-2ded-11e8-85ce-eb9243d8ca3b.png">

So my request would be to have this properly supported, just like in [here](http://react.carbondesignsystem.com/?selectedKind=TextInput&selectedStory=invalid&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel). There is a workaround the visual bug by leveraging the ::placeholder selector.

And if it's possible to have a function to change the text input 
```js
this.changeInput('I am the text now!')
```
it would be great!

> Is this issue related to a specific component?

Text input

> What browser are you working in?

Chrome latest version.

> What version of the Carbon Design System and carbon-addons-ics are you using?

latest?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

No release dates, it's for connections theme customization.

**Comment by j1mie** [comment]
@denizsokullu Hoping this answers this for you, closing for now!
