### ISSUE TITLE
Webpack throws an error after adding the index.scss due to extensions resolution

### ISSUE THREAD

**Issue by bazquezero** [carbon-design-system/carbon-addons-ics#38]
Hello!
I'm using the Carbon design system for React.js development, looking at the addons, I have found that this is the only one that throws an error when adding the **index.scss** file.

```
Module build failed:
import warning from 'warning';
^
      Invalid CSS after "i": expected 1 selector or at-rule, was "import warning from"
      in ./node_modules/carbon-addons-ics/node_modules/carbon-components/src/components/card/card.js (line 1, column 1)
```

As this looked to be an error from the dependency inside this addon, I edited the **_card.scss** file from this repository

This
`@import 'carbon-components/src/components/card/card';`
To this
`@import 'carbon-components/src/components/card/_card.scss;'`

And it worked for the card file! but then throwed another error because the checkbox file is also importing a component from the dependency within this repo.

I'm not sure if it is a lack of config parameters on my Webpack file, but the other addons work just fine, and my config looks like the one you used in the *.storybook* folder

**PD** This is my first time typing an issue, if I did not make myself clear please let me know :smile:

**Comment by j1mie** [comment]
Thanks so much for looking at this @bazquezero 🎉 

Would you be able to open a PR for this one?
